messages:
  create-party: '[Party] パーティーを作成しました'
  delete-party: '[Party] パーティーを削除しました'
  already-joined-party: '[Party] 既にパーティーに入っています！ (%user% のパーティー)'
  toggle-chat-on: '[Party] パーティーチャットをオンにしました'
  toggle-chat-off: '[Party] パーティーチャットをオフにしました'
  not-owner: '[Party] あなたはこのパーティーのオーナーではありません！'
  party-chat: '[Party] <%name%>: %chat%'