settings:
  invite-delete-ticks: 3600
messages:
  create-party: '[Party] パーティーを作成しました'
  delete-party: '[Party] パーティーを削除しました'
  disband-party: '[Party] パーティーは解散されました'
  leave-party: '[Party] パーティーを抜けました'
  leave-party-everyone: '[Party] %user% がパーティーを抜けました'
  cannot-leave-party-owner:
    - '[Party] あなたはこのパーティーのオーナーです！'
    - '/party delete を実行してパーティーを削除してください！'
  this-user-already-joined-party: '[Party] 招待しようとしたプレイヤーは既にパーティーに入っています！'
  already-joined-party: '[Party] 既にパーティーに入っています！ (%owner% のパーティー)'
  already-invited-party: '[Party] 既にパーティーに招待しています！'
  joined-party: '[Party] %owner% のパーティーに参加しました！'
  joined-party-everyone: '[Party] %user% がパーティーに参加しました！'
  invite-party: '[Party] %user% をパーティーに招待しました！'
  invite-expire:
    - '[Party] %owner% のパーティー招待が無効になりました'
  invite-expire-everyone:
    - '[Party] %user% のパーティーの招待が無効になりました'
  invite-party-target:
    - '[Party] %owner% にパーティーを招待されました！'
    - '/party join %owner% で参加可能です'
  toggle-chat-on: '[Party] パーティーチャットをオンにしました'
  toggle-chat-off: '[Party] パーティーチャットをオフにしました'
  not-party-owner: '[Party] あなたはこのパーティーのオーナーではありません！'
  not-joined-party: '[Party] あなたはパーティーに参加していません！'
  not-founded-party: '[Party] パーティーが見つかりませんでした・・・！'
  party-chat: '[Party] <%user%>: %chat%'